# ROOT CONFIGURATION
watch_stylesheet: true
watch_config: true
debug: false

# TRAY MENU KOMOREBI
komorebi:
  start_command: "komorebic start --whkd"
  stop_command: "komorebic stop --whkd"
  reload_command: "komorebic reload-configuration"

# BARS CONFIGURATION
bars:
  status-bar:
    enabled: true
    screens: ['LG ULTRAGEAR'] 
    class_name: "yasb-bar"
    alignment:
      position: "bottom"
      center: false
    blur_effect:
      enabled: false
      acrylic: false
      dark_mode: true
      round_corners: false
      border_color: System
    window_flags:
      always_on_top: false
      windows_app_bar: false
    dimensions:
      width: "100%"
      height: 20
    padding:
      top: 1
      left: 0
      bottom: 4
      right: 10
    widgets:
      left: [
          # "komorebi_workspaces",
           "komorebi_workspaces2",
           "komorebi_active_layout",
           "active_window2",
          # "whkd",
          #windows_workspaces,
          # "wallpapers",
          # "apps",
          # "taskbar",
        ]
      center: [
          #"clock",
          "clock2",
          #"media",
        ]
      right: [
          #"battery",
          #"traffic",
          #"ip_info",
          # "update_check",
          #"weather",
          #"weather2",          
          #"cpu",
          "cpu2",
          #"memory",
          "memory2",
          #"nvidia_temp",
          #"disk",
          #"volume",
          "volume2",
        ]

widgets:



  battery:
    type: "yasb.battery.BatteryWidget"
    options:
      label: "<span>{icon}</span>{percent}%"
      label_alt: "{icon} {percent}% | time: {time_remaining}"
      charging_options:
        icon_format: "{charging_icon}"
      status_thresholds: {critical: 10, low: 20, medium: 40, high: 50, full: 60}
    
  # KOMOREBI WORKSPACES WIDGET
  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: "\udb81\udc3d"
      label_workspace_active_btn: "{name}"
      label_workspace_populated_btn: "\udb81\udc3e"
      label_default_name: ""
      label_zero_index: false
      hide_empty_workspaces: false
      hide_if_offline: true
      animation: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
        
  komorebi_workspaces2:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
        label_offline: "Komorebi Offline"
        label_workspace_btn: "{index}"
        label_workspace_active_btn: "{index}"
        label_workspace_populated_btn: "{index}"
        label_default_name: "{index}"
        label_float_override: "\ueb23 Float Active"
        label_zero_index: false
        hide_empty_workspaces: true
        hide_if_offline: false
        animation: false
        container_padding:
          top: 0
          left: 8
          bottom: 0
          right: 8        
        

  # KOMOREBI ACTIVE LAYOUT WIDGET
  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts:
        [
          "bsp",
          "columns",
          "rows",
          "grid",
          "vertical_stack",
          "horizontal_stack",
          "ultrawide_vertical_stack",
          "right_main_vertical_stack",
        ]
      layout_icons:
        bsp: "BSP"
        columns: "COLS"
        rows: "ROWS"
        grid: "GRID"
        vertical_stack: "V-STACK"
        horizontal_stack: "H-STACK"
        ultrawide_vertical_stack: "UW-STACK"
        right_main_vertical_stack: "RMV-STACK"
        monocle: "MONOCLE"
        maximised: "MAX"
        floating: "FLOATING"
        paused: "PAUSED"
      callbacks:
        on_left: "prev_layout"
        on_middle: "toggle_monocle"
        on_right: "next_layout"

  # WINDOWS DESKTOPS WIDGET
  windows_workspaces:
    type: "yasb.windows_desktops.WorkspaceWidget"
    options:
      label_workspace_btn: "\udb80\udea0" # \uecca
      label_workspace_active_btn: "\udb82\udfaf" # \udb82\udfaf,\ueccb
      switch_workspace_animation: true
      animation: false
      container_padding: 
        top: 0
        left: 10
        bottom: 0
        right: 0

  # ACTIVE WINDOW TITLE WIDGET
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 16
      max_length: 70
      max_length_ellipsis: "..."
      monitor_exclusive: true
      animation:
        enabled: false
        
  active_window2:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: ""
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 16
      max_length: 56
      max_length_ellipsis: "..."
      monitor_exclusive: true          

  # CLOCK WIDGET
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %d. %b  —  %H:%M}" # label: "{%a %d, %b %H:%M}"
      label_alt: "{%A, %d. %B %Y  —  %H:%M:%S}" # label_alt: "{%A %d %B %Y, %H:%M}"
      locale: "de_DE" # Langugae for date, you can set your own, example fr_FR
      update_interval: 1000
      timezones: [] # timezones: ["America/Montreal"]
      calendar: 
        blur: true
        round_corners: true
        round_corners_type: 'normal'
        border_color: 'System'
        alignment: 'center'
        direction: 'down'
        distance: 6
      animation:
        enabled: false
      callbacks:
        on_left: "toggle_label"
        on_middle: "toggle_calendar"
        on_right: "do_nothing"
        
  clock2:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a %d, %b %H:%M}"
      label_alt: "{%A %d %B %Y, %H:%M}"
      #locale: 'no_NO' # Langugae for date, you can set your own, example fr_FR
      update_interval: 1000
      timezones: [] #Looking up time zone info from registry
      #timezones: [CET] ["America/Montreal"]
      callbacks:
        on_left: "toggle_label"
        on_middle: "toggle_calendar"
        on_right: "do_nothing"  

  # MEDIA WIDGET
  media:
    type: "yasb.media.MediaWidget"
    options:
      label: "{title}"
      label_alt: "{title} - {artist}"
      max_field_size:
        label: 30
        label_alt: 50
      show_thumbnail: false
      controls_only: false
      controls_left: true
      hide_empty: true
      thumbnail_alpha: 100
      thumbnail_padding: 0
      thumbnail_corner_radius: 0
      animation:
        enabled: false
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      icons:
        prev_track: "\ue100"
        next_track: "\ue101"
        play: "\ue102"
        pause: "\ue103"

  # WHKD WIDGET
  whkd:
    type: "yasb.whkd.WhkdWidget"
    options:
      label: "<span>\uf11c</span>"

  # TRAFFIC WIDGET
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<div style=\"text-align:right; width:80px;\">{upload_speed} \u25b2</div><div style=\"text-align:right;\">{download_speed} \u25bc</div>"
      label_alt: "<div style=\"text-align:right; width:80px;\">{upload_speed} \u25b2</div><div style=\"text-align:right;\">{download_speed} \u25bc</div>"
      update_interval: 1000
      callbacks:
        on_left: "do_nothing"
        on_middle: "do_nothing"
        on_right: "do_nothing"

  # IP ADDRESS WIDGET
  ip_info:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span>\ud83d\ude80</span>" #\udb82\ude60
      label_alt: "<span>\ud83d\ude80</span>{data[ip]}" #\udb82\ude60
      class_name: "ip-info-widget"
      exec_options:
        run_cmd: "curl.exe https://ipinfo.io"
        run_interval: 120000 # every 5 minutes
        return_format: "json"
      animation:
        enabled: false
      callbacks:
        on_left: "toggle_label"
        on_middle: "exec cmd /c ncpa.cpl" # open network settings
        on_right: "exec cmd /c start https://ipinfo.io/{data[ip]}" # open ipinfo in browser

  # WINGET/WINDOWS UPDATE WIDGET
  update_check:
    type: "yasb.update_check.UpdateCheckWidget"
    options:
      windows_update:
        enabled: true
        label: "<span>\uf0ab</span> {count}"
        interval: 240
        exclude: []
      winget_update:
        enabled: true
        label: "<span>\uf0ab</span> {count}"
        interval: 60
        exclude: []

  # CPU WIDGET
  cpu:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "<span><img src='C:\\Users\\Slim08\\.config\\yasb\\icons\\cpu.svg'/></span>{info[percent][total]}%" # \uf2db
      label_alt: "<span><img src='C:\\Users\\Slim08\\.config\\yasb\\icons\\graph.svg'/></span>{info[histograms][cpu_percent]}" # \uf437
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      animation:
        enabled: false
      callbacks:
        on_left: "toggle_label"
        on_middle: "exec cmd /c Taskmgr"
        on_right: "do_nothing"
        
  cpu2:
    type: "yasb.cpu.CpuWidget"
    options:
      label: "cpu {info[percent][total]}%"
      label_alt: "<span>\uf437</span> {info[histograms][cpu_percent]}"
      update_interval: 2000
      histogram_icons:
        - '\u2581' # 0%
        - '\u2581' # 10%
        - '\u2582' # 20%
        - '\u2583' # 30%
        - '\u2584' # 40%
        - '\u2585' # 50%
        - '\u2586' # 60%
        - '\u2587' # 70%
        - '\u2588' # 80%+
      histogram_num_columns: 8
      callbacks:
        on_right: "exec cmd /c Taskmgr"        

  # MEMORY WIDGET
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span><img src='C:\\Users\\Slim08\\.config\\yasb\\icons\\memory.svg'/></span>{virtual_mem_percent}%" # \uefc5
      label_alt: "<span><img src='C:\\Users\\Slim08\\.config\\yasb\\icons\\memory.svg'/></span>{virtual_mem_used}B | {virtual_mem_total}B" # \uefc5
      update_interval: 5000
      animation:
        enabled: false
      callbacks:
        on_left: "toggle_label"
        on_middle: "do_nothing"
        on_right: "do_nothing"
      memory_thresholds:
        low: 25
        medium: 50
        high: 90
        
  memory2:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "mem {virtual_mem_percent}%"
      label_alt: "mem {virtual_mem_free}"
      update_interval: 10000
      callbacks:
        on_right: "exec cmd /c Taskmgr"         

  # NVIDIA GPU TEMP WIDGET
  nvidia_temp:
    type: "yasb.custom.CustomWidget"
    options:
      label: "<span><img src='C:\\Users\\Slim08\\.config\\yasb\\icons\\gpu.svg'/></span>{data}°C" # \udb82\udcae
      label_alt: "<span><img src='C:\\Users\\Slim08\\.config\\yasb\\icons\\gpu.svg'/></span>{data}°C" # \udb82\udcae
      class_name: "system-widget"
      exec_options:
        run_cmd: "powershell nvidia-smi --query-gpu=temperature.gpu --format=csv,noheader"
        run_interval: 10000 # run every 10 sec
        return_format: "string"
      callbacks:
        on_left: "do_nothing"
        on_middle: "exec C:/Program Files/WindowsApps/NVIDIACorp.NVIDIAControlPanel_8.1.966.0_x64__56jybvy8sckqj/nvcplui.exe"
        on_right: "do_nothing"

  # DISK WIDGET
  disk:
    type: "yasb.disk.DiskWidget"
    options:
      label: "<span>\ud83d\udcbe</span>({volume_label}:) {space[used][percent]}" # \udb80\udeca
      label_alt: "<span>\ud83d\udcbe</span>({volume_label}:) {space[used][gb]} | {space[total][gb]}" # \udb80\udeca
      volume_label: "C"
      update_interval: 60
      group_label:
        volume_labels: ["C", "D", "E", "F"]
        show_label_name: true
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "System"
        alignment: "right"
        direction: "down"
        distance: 6
      animation:
        enabled: false
      callbacks:
        on_left: "toggle_label"
        on_middle: "exec explorer C:\\" # Open disk C in file explorer
        on_right: "do_nothing"

  # WEATHER WIDGET
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span>{temp}"
      label_alt: "<span>{icon}</span>Min {min_temp} | Max {max_temp} | rF {humidity}"
      api_key: "3ce31daec3cb4390967233226251401" # Get your free API key from https://www.weatherapi.com/
      update_interval: 600 # Update interval in seconds, Min 600 seconds
      hide_decimal: true
      units: "metric" # Can be 'metric' or 'imperial'
      location: "Germany Hallbergmoos 85399" # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      animation:
        enabled: false
      callbacks:
        on_left: "toggle_label"
        on_middle: "toggle_card"
        on_right: "do_nothing"
      icons:
        sunnyDay: "<img src='C:\\Users\\Slim08\\.config\\yasb\\icons\\Weather\\sunnyDay.svg'/>" # \ue30d
        clearNight: "<img src='C:\\Users\\Slim08\\.config\\yasb\\icons\\Weather\\clearNight.svg'/>" # \ue32b
        cloudyDay: "<img src='C:\\Users\\Slim08\\.config\\yasb\\icons\\Weather\\cloudyDay.svg'/>" # \ue302
        cloudyNight: "<img src='C:\\Users\\Slim08\\.config\\yasb\\icons\\Weather\\cloudyNight.svg'/>" # \ue37e
        rainyDay: "<img src='C:\\Users\\Slim08\\.config\\yasb\\icons\\Weather\\rainyDay.svg'/>" # \ue308
        rainyNight: "<img src='C:\\Users\\Slim08\\.config\\yasb\\icons\\Weather\\rainyNight.svg'/>" # \ue325
        snowyIcyDay: "<img src='C:\\Users\\Slim08\\.config\\yasb\\icons\\Weather\\snowyIcyDay.svg'/>" # \ue30a
        snowyIcyNight: "<img src='C:\\Users\\Slim08\\.config\\yasb\\icons\\Weather\\snowyIcyNight.svg'/>" # \ue327
        blizzard: "<img src='C:\\Users\\Slim08\\.config\\yasb\\icons\\Weather\\blizzard.svg'/>" # \ue314
        default: "<img src='C:\\Users\\Slim08\\.config\\yasb\\icons\\Weather\\default.svg'/>" # \uebaa
      weather_card: 
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        distance: 6
        icon_size: 64

  weather2:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: '3bf4cf9a7c3f40d6b31174128242807' # Get your free API key from https://www.weatherapi.com/
      update_interval: 600 # Update interval in seconds, Min 600 seconds
      hide_decimal: true
      units: "metric"
      location: 'Norway Kristiansand 4610' # You can use "USA Los Angeles 90006" {COUNTRY CITY ZIP_CODE}, or just city.
      callbacks:
        on_left: "toggle_label"
      icons: 
        sunnyDay: "\ue30d"
        clearNight: "\ue32b"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\ue311"
        rainyDay: "\udb81\ude7e"
        rainyNight: "\udb81\ude7e"
        snowyIcyDay: "\udb81\udd98"
        snowyIcyNight: "\udb81\udd98"
        blizzard: "\uebaa"
        default: "\uebaa"
        # https://www.weatherapi.com/docs/
        # Usage {temp_c}, {min_temp_c}, {max_temp_c}, {temp_f}, {min_temp_f}, {max_temp_f}, {location}, {humidity}, {icon}, {conditions}



  # VOLUME WIDGET
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span>{level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ud83d\udd07" # \ueee8 Icon for muted
        - "\ud83d\udd08" # \uf026 Icon for 0-10% volume
        - "\ud83d\udd09" # \uf027 Icon for 11-30% volume
        - "\ud83d\udd09" # \uf027 Icon for 31-60% volume
        - "\ud83d\udd0a" # \uf028 Icon for 61-100% volume
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: 'normal'
        border_color: 'System'
        alignment: 'right'
        direction: 'down'
        distance: 6
      animation:
        enabled: false
      callbacks:
        on_left: "toggle_mute"
        on_middle: "toggle_volume_menu"
        on_right: "exec cmd.exe /c nircmd sendkeypress ctrl+shift+a"
        
  volume2:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      callbacks:
        on_left: "exec cmd.exe /c start ms-settings:apps-volume"
        on_right: "exec cmd.exe /c start ms-settings:sound"        
        

  # CUSTOM APPS WIDGET
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      label: "{data}"
      app_list:
        - { icon: "\uf422", launch: "search" }
        - { icon: "\uf422", launch: "%userprofile%/scoop/apps/flow-launcher/current/Flow.Launcher.exe" }
        - { icon: "\udb84\udf55", launch: "widget" }
        - { icon: "\ue690", launch: "quick_settings" }
        - { icon: "\uf0a2", launch: "notification_center" }
        - { icon: "\uf46a", launch: "cmd.exe /c start ms-settings:windowsupdate" }
      container_padding:
        top: 0
        left: 4
        bottom: 0
        right: 4

  # TASKBAR WIDGET
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      icon_size: 16
      animation: true
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0

  # CUSTOM WINDOWS BUTTON WIDGET
  win_button:
    type: "yasb.custom.CustomWidget"
    options:
      label: "\ue62a"
      label_alt: "\ue62a"
      class_name: "win-button-widget"
      callbacks:
        on_left: "exec start_menu"
        on_middle: "do_nothing"
        on_right: "exec explorer.exe shell:::{D20EA4E1-3957-11d2-A40B-0C5020524153}"

  # WALLPAPERS GALLERY WIDGET
  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\udb83\ude09</span>"
      image_path: "C:\\Users\\Slim08\\Pictures\\4k Abstract Wallpaper"
      change_automatically: false
      update_interval: 60
      gallery:
        enabled: true
        blur: true
        image_width: 220
        image_per_page: 8
        show_buttons: true
        orientation: "portrait"
        image_spacing: 8
        lazy_load: true
        lazy_load_delay: 80
        lazy_load_fadein: 400
        image_corner_radius: 20
        enable_cache: true
      run_after:
        # - "wal -s -t -e -q -n -i {image}", # Example command to run after wallpaper is updated
        # - "cmd.exe /c start /min pwsh ./yasb.ps1", # Example command to run after wallpaper is updated
